"""Packaging verified analysis into self-contained, reproducible proof bundles."""
from __future__ import annotations

import json
import shutil
from pathlib import Path

from src.schemas import Answer


def build_proof_bundle(answer: Answer, data_dir: str | Path, out_dir: str | Path) -> Path:
    """Create a self-contained proof bundle that can be independently re-run.

    The bundle contains:
    - data/: Copy of all CSV files from data_dir
    - manifest.json: Metadata including question, verdict, claimed values, and data hash
    - proof.py: Standalone verification script (requires only pandas and numpy)

    Args:
        answer: Fully verified Answer schema instance.
        data_dir: Directory containing input data CSVs.
        out_dir: Target directory to write the bundle into.

    Returns:
        Path to the generated proof bundle directory.

    Raises:
        ValueError: If answer has no proof attached.
        FileNotFoundError: If data_dir does not exist.
    """
    if answer.proof is None:
        raise ValueError("Cannot build proof bundle for an answer with no proof")

    data_src = Path(data_dir).resolve()
    if not data_src.is_dir():
        raise FileNotFoundError(f"Source data directory not found: {data_src}")

    out_path = Path(out_dir).resolve()
    out_path.mkdir(parents=True, exist_ok=True)

    # 1. Copy CSV files into out_dir/data/
    data_dst = out_path / "data"
    data_dst.mkdir(parents=True, exist_ok=True)
    for csv_file in sorted(data_src.glob("*.csv")):
        shutil.copy2(csv_file, data_dst / csv_file.name)

    # 2. Write out_dir/manifest.json
    manifest = {
        "question": answer.question,
        "verdict": answer.verdict.value if hasattr(answer.verdict, "value") else str(answer.verdict),
        "values": [v.model_dump() for v in answer.values],
        "data_hash": answer.proof.data_hash,
    }
    (out_path / "manifest.json").write_text(json.dumps(manifest, indent=2), encoding="utf-8")

    # 3. Write out_dir/proof.py (standalone verification script)
    stored_code = answer.proof.code
    expected_values = {v.label: v.value for v in answer.values}

    proof_script = f'''"""Standalone proof-carrying data analysis verification script.

Auto-generated by Proof-Carrying Data Analyst.
Requires only pandas and numpy.
"""
import json
import math
import sys
from pathlib import Path

import numpy as np
import pandas as pd

DATA_DIR = Path(__file__).resolve().parent / "data"
if not DATA_DIR.is_dir():
    print("MISMATCH: Data directory not found", file=sys.stderr)
    sys.exit(1)

# Load CSV tables exactly like ingest
dfs = {{p.stem: pd.read_csv(p) for p in sorted(DATA_DIR.glob("*.csv"))}}

USER_CODE = {stored_code!r}

scope = {{"dfs": dfs, "pd": pd, "np": np}}
try:
    exec(USER_CODE, scope)
except Exception as exc:
    print(f"MISMATCH: Execution failed: {{exc}}", file=sys.stderr)
    sys.exit(1)

if "result" not in scope or not isinstance(scope["result"], dict):
    print("MISMATCH: Variable 'result' is missing or not a dict", file=sys.stderr)
    sys.exit(1)

raw_result = scope["result"]
cleaned_result = {{}}
for k, v in raw_result.items():
    if isinstance(v, (np.integer, np.floating, np.bool_)):
        v = v.item()
    cleaned_result[k] = v

# Print the reproduced result as JSON
print(json.dumps(cleaned_result))

# Assert each expected value matches within numerical tolerance
EXPECTED = {expected_values!r}

for label, exp_val in EXPECTED.items():
    if label not in cleaned_result:
        print(f"MISMATCH: Label '{{label}}' not found in result", file=sys.stderr)
        sys.exit(1)

    act_val = cleaned_result[label]
    matches = False
    if isinstance(exp_val, (int, float)) and isinstance(act_val, (int, float)):
        matches = math.isclose(float(exp_val), float(act_val), rel_tol=1e-6, abs_tol=1e-9)
    else:
        matches = str(exp_val) == str(act_val)

    if not matches:
        print(
            f"MISMATCH: Label '{{label}}' expected {{exp_val!r}} but got {{act_val!r}}",
            file=sys.stderr,
        )
        sys.exit(1)

print("REPRODUCED")
'''
    (out_path / "proof.py").write_text(proof_script, encoding="utf-8")
    return out_path
